export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
export const RESET_INGREDIENTS = 'RESET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILURE = 'PURCHASE_BURGER_FAILURE';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';

export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

/** Sagas initialization action types */
export const AUTH_CHECK_TIMEOUT = 'auth/checkTimeout';
export const AUTH_CHECK_STATE = 'auth/checkState';
export const AUTH_INITIATE_LOGOUT = 'auth/initiateLogout';
export const AUTH_USER = 'AUTH_USER';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';
export const PURCHASE_BURGER = 'PURCHASE_BURGER';
export const FETCH_ORDERS = 'FETCH_ORDERS';
